language: android
sudo: required
android:
  components:
    - tools
    - platform-tools
    - tools
    - build-tools-26.0.1
    - android-19
    - android-26
    - extra-android-m2repository
    - extra-m2repository
    - #sys-img-arm64-v8a-google_apis-25  #Requires SDK Platform Android API 25
    - sys-img-armeabi-v7a-google_apis-19
jdk:
  - oraclejdk8
env:
  matrix:
    - ANDROID_SDKS=android-19,sysimg-19  ANDROID_TARGET=android-19  ANDROID_ABI=armeabi-v7a
before_install:
  - echo no | android create avd --force -n test -t $ANDROID_TARGET --abi $ANDROID_ABI
  - emulator -avd test -no-audio -no-window &
before_script:
  - android-wait-for-emulator
  - adb shell input keyevent 82 &

script:
  - ./gradlew build connectedCheck --stacktrace

licenses:
    - 'android-sdk-preview-license-.+'
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'
