language: android
jdk: oraclejdk8
env:
  global:
    - ANDROID_TARGET=android-22
    - ANDROID_ABI=armeabi-v7a
android:
  components:
  - tools
  - platform-tools
  - build-tools-26.0.1
  - android-22
  - android-26
  - extra-android-m2repository
  - sys-img-${ANDROID_ABI}-${ANDROID_TARGET}

#before_script:
  - #chmod +x gradlew
  - #android list targets
  - #android list sdk --extended --no-ui --all
  - #echo "y" | android update sdk -a --no-ui --filter sys-img-arm64-v8a-google_apis-25  #works but focus error
  - #echo "y" | android update sdk -a --no-ui --filter sys-img-armeabi-v7a-google_apis-22
  - #android list targets
  - #echo "n" | android create avd --name myandroid25 -t "android-25" --abi "google_apis/arm64-v8a"  #works but focus error
  - #echo "n" | android create avd --name myandroid22 -t "android-22" --abi "google_apis/armeabi-v7a"
  - #emulator -avd myandroid22 -no-window &
  - #android-wait-for-emulator
  - #adb shell input keyevent 82 &

script:
  - #./gradlew build jacocoTestReport assembleAndroidTest
  - echo no | android create avd --force -n test -t $ANDROID_TARGET --abi $ANDROID_ABI
  - emulator -avd test -no-audio -no-window &
  - android-wait-for-emulator
  - adb shell setprop dalvik.vm.dexopt-flags v=n,o=v
  - adb shell input keyevent 82 &
  - ./gradlew connectedCheck
