language: android
sudo: required
android:
  components:
    - tools
    - platform-tools
    - build-tools-26.0.1
    - tools
    - android-19
    - android-26
    - extra-android-m2repository
    - extra-m2repository
    - sys-img-arm64-v8a-google_apis-25  #Requires SDK Platform Android API 25
jdk:
  - oraclejdk8

env:
 global:
 - ADB_INSTALL_TIMEOUT=3 # minutes

before_script:
  - chmod +x gradlew
  - #android list targets
  - android list sdk --extended --no-ui --all
  - #echo "y" | android update sdk -a --no-ui --filter sys-img-arm64-v8a-google_apis-25  #works but focus error
  - echo "y" | android update sdk -a --no-ui --filter sys-img-armeabi-v7a-google_apis-19
  - android list targets
  - #echo "n" | android create avd --name myandroid25 -t "android-25" --abi "google_apis/arm64-v8a"  #works but focus error
  - echo "n" | android create avd --name myandroid19 -t "android-19" --abi "google_apis/armeabi-v7a"
  - emulator -avd myandroid19 -no-window &
  - android-wait-for-emulator
  #
  - adb shell input keyevent 82 &

script:
  - ./gradlew build connectedCheck --stacktrace

licenses:
    - 'android-sdk-preview-license-.+'
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'
